name: build build-system

env:
  NETCORE_VERSION: 5.0.101
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches:
    - main
    paths:
      - ".github/workflows/build.yml"
      - "build-system/*"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout build-system
      uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - id: nuke
      uses: cloud-tek/actions/build-system@v0.4
      name: nuke
      with:
        directory: ${{ github.workspace }}/main
        Compile: 'true'
        UnitTests: 'true'