name: build build-system

env:
  NETCORE_VERSION: 5.0.101
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches:
    - main
    - feature/**
    - release/**
    paths:
      - ".github/workflows/build.yml"
      - "build/*"
      - "build-system/*"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    # note: actions/checkout@v2 uses shallow cloning, gitver requires full clone
    - name: Checkout build-system
      uses: actions/checkout@v1
      # with:
      #   path: main
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - id: nuke
      uses: cloud-tek/actions/build-system@v0.6
      name: nuke
      with:
        directory: ${{ github.workspace }}
        Compile:      'true'
        Pack:         'true'
        Push:         'true'
        NuGetApiUrl:  'nuget.pkg.github.com'
        NuGetApiKey:  '${{ secrets.GH_PAT }}'
    - name: diag
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
       apt update && apt install tree --yes
       tree