name: build build-system

env:
  NETCORE_VERSION: 5.0.101
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  pull_request:
    branches:
      - main
      - release/**
  push:
    branches:
    - main
    - feature/**
    - release/**
    paths:
      - ".github/workflows/build.yml"
      - "build/**"
      - "build-system/**"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: dotnet tool restore
      run: dotnet tool restore
      shell: bash
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - name: check pull_request.head.ref
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged }}
      run: |
        BRANCH="${{ github.event.pull_request.head.ref }}"
        if [[ $BRANCH =~ (release\/)([0-9]+\.[0-9]+)(\.[0-9]+)? ]]
        then
          echo "::set-env name=version::${BASH_REMATCH[2]}"
        fi
      shell: bash
    - name: tag (pull_request.head.ref)
      if: ${{ env.version != null }}
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        RELEASE_BRANCHES: master
        INITIAL_VERSION: 0.1.0
        CUSTOM_TAG: ${{ env.version }}
        VERBOSE: true
    - name: gitversion
      shell: bash
      if: always()
      working-directory: ${{ github.workspace }}
      run: |
       dotnet gitversion
    - id: buld-system
      if: github.event_name != 'pull_request'
      uses: cloud-tek/actions/build-system@v0.6
      name: build-system
      with:
        directory: ${{ github.workspace }}
        Compile:      'true'
        Pack:         'true'
        Push:         'true'
        NuGetApiUrl:  'https://nuget.pkg.github.com/cloud-tek/index.json'
        NuGetApiKey:  '${{ secrets.GH_PAT }}'
    - id: buld-system-pr
      if: github.event_name == 'pull_request'
      uses: cloud-tek/actions/build-system@v0.6
      name: build-system (pr)
      with:
        directory: ${{ github.workspace }}
        Compile:      'true'
    - name: gitversion
      shell: bash
      if: always()
      working-directory: ${{ github.workspace }}
      run: |
       dotnet gitversion
    - name: diag
      shell: bash
      if: always()
      working-directory: ${{ github.workspace }}
      run: |
       apt update && apt install tree --yes
       tree